<?php

return [
    'dashboard' => [
        'aShowStatisticsNumbers',
        'aShowStatisticsCategoryProducts',
        'aShowStatisticsStoreTypes',
        'aShowStatisticsPopularProducts',
        'aShowPopularStores',

        'aIndexProductsForSelection',
        'aShowProductDetails',
        'aApprovePendingProduct',
        'aIndexProducts',
        'aIndexOwnersForSelection',
        'aIndexOwnersForSelection',
        'aShowProductInfo',

        'aShowStoreDetails',
        'aIndexProductStock',
        'aIndexProductBundles',
        'aProductsExport',
        'aProductsEditInfo',
        'aEditStoreDetails',
        'aEditProductStock',
        'aEditProductBundle',
        'aAddSupplierProduct',
        'aAddRetailerProduct',


        'aShowOrders',
        'aIndexOrder',
        'aShowProductPackage',
        'aOrdersExport',
        'aIndexOrdersStatues',
        'aIndexOrdersPendingSellers',

        'aIndexAdmins',
        'aAddAdmin',
        'aIndexAdmins',
        'aShowAdmin',
        'aEditAdmin',
        'aDeleteAdmin',
        'aDeleteAdminImage',
        'aAdminsExport',

        'aIndexSuppliers',
        'aShowSupplier',
        'aEditSuppliers',
        'aDeleteSuppliers',

        'aIndexSellersForSelection',
        'aIndexSellers',
        'aShowSeller',
        'sApprovePendingSeller',
        'aIndexSellers',
        'aShowSeller',
        'aEditSellers',
        'aDeleteSellers',
        'aSellersExport',

        'aShowConsumer',
        'aIndexConsumers',
        'aAddConsumers',
        'aEditConsumers',
        'aDeleteConsumers',
        'aIndexCategoriesForAdmin',
        'aIndexCategoriesForSelection',

        'aIndexParentAndSub',
        'aShowCategory',
        'aIndexCategories',
        'aAddCategory',
        'aEditCategory',
        'aDeleteCategory',
        'aIndexCategories',
        'aCategoriesExport',
        'aDeleteCategoryImage',

        'aIndexPackingUnitsForSelection',
        'aShowPackingUnit',
        'aIndexPackingUnits',
        'aAddPackingUnits',
        'aEditPackingUnits',
        'aDeletePackingUnits',

        'aIndexStoreTypesForSelection',
        'aIndexStores',
        'aIndexStoresForSelection',
        'aShowStoreData',
        'aShowStoreDetails',
        'aIndexStoreByUserId',
        'aShowStoreById',
        'aIndexStoreMainAddress',
        'aEditStore',
        'aEditStoreAddress',
        'aDeleteStore',
        'aIndexStoreCoverArea',
        'aIndexForSelection',
        'aStoresExport',

        'aShowShoppingCart',
        'aIndexShoppingCart',
        'aAddShoppingCart',
        'aEditShoppingCart',
        'aDeleteShoppingCart',

        'aIndexCountriesForSelection',
        'aShowCountries',
        'aIndexCountries',
        'aAddCountries',
        'aEditCountries',
        'aDeleteCountries',
        'aCountriesExport',

        'aIndexRegionsForSelection',
        'aShowRegion',
        'aIndexRegions',
        'aAddRegions',
        'aEditRegions',
        'aDeleteRegions',
        'aRegionsExport',

        'aIndexStatesForSelection',
        'aShowState',
        'aIndexState',
        'aAddState',
        'aEditState',
        'aDeleteState',
        'aStatesExport',

        'aIndexCitiesForSelection',
        'aShowCity',
        'aIndexCity',
        'aAddCity',
        'aEditCity',
        'aDeleteCity',
        'aCitiesExport',

        'aIndexAreasForSelection',
        'aShowAreas',
        'aIndexAreas',
        'aAddAreas',
        'aEditAreas',
        'aDeleteAreas',

        'aIndexZonesForSelection',
        'aShowZone',
        'aIndexZone',
        'aAddZone',
        'aEditZone',
        'aDeleteZone',

        'aIndexAppTvTypes',
        'aIndexAppTvLocations',
        'aIndexAppTvs',
        'aShowAppTv',
        'aAddAppTv',
        'aEditAppTv',
        'aDeleteAppTv',
        'aAppTvsExport',
        'aIndexAppsForSelection',

        'aIndexHomeSections',
        'aShowHomeSections',
        'aAddHomeSections',
        'aEditHomeSections',
        'aDeleteHomeSections',

        'aAddBrands',
        'aIndexBrands',
        'aIndexBrands',
        'aShowBrands',
        'aEditBrands',
        'aDeleteBrands',
        'aBrandsExport',

        'aIndexPermissions',
        'aIndexPermissionsForAdmin',
        'aIndexRolePermissions',
        'aTogglePermissions',

        'aIndexSizes',
        'aAddSize',
        'aEditSize',
        'aDeleteSize',
        'aIndexSizeTypes',
        'aShowSize',
        'aIndexCategories',
        'aSizesExport',

        'aIndexOffers',
        'AddOffer',
        'EditOffer',
        'DeleteOffer',
        'ShowOffer',
        'aIndexOfferTypesForSelection',
        'aIndexOfferTypesForSelection',

        'aIndexSystemSetup',
        'aEditSystemSetup',
        'aDeleteSystemSetup',
        'aShowSystemSetup',

        'aIndexColors',
        'aIndexColors',
        'aShowColors',
        'aAddColors',
        'aEditColors',
        'aDeleteColors',
        'aColorsExport',

        'aIndexMaterials',
        'aShowMaterial',
        'aDeleteMaterials',
        'aAddMaterials',
        'aEditMaterials',
        'aMaterialsExport',

        'aIndexLogs',
        'aShowLog',
        'aIndexLogs',

    ],
    'seller' => [
        'sAddStoreRate',
        'sAddStoreImage',
        'sAddStoreCover',
        'sDeleteStoreImage',

        'sShowProductsStatistics',
        'sShowProductsStatisticsCharts',
        'sShowOrderStatistics',
        'sShowOrdersStatisticsCharts',

        'sEditProfile',
        'sEditStoreCategories',
        'sEditFeedLink',
        'sRateStore',
        'sRateProduct',
        'sToggleFavoriteStore',
        'sMakeStoreCall',

        'sIndexFavoriteProducts',

        'sGetStoreCoverArea',
        'sAddCoverArea',
        'sEditCoverArea',
        'sDeleteCoverArea',

        'sShowAllInventory',
        'sShowProductInventory',
        'sAddDiscount',
        'sIncreaseStock',
        'sSwitchProductActivation',
        'sShowStatus',
        'sToggleActiveProduct',
        'sEditInventoryInfo',
        'sEditBarcode',
        'sEditStock',
        'sEditPackage',
        'sEditStoreDetails',
        'sAddImage',
        'sAddBundle',
        'sDeleteImage',
        'sDeleteBundlePrice',
        'sIndexNonCompletedProducts',
        'sDeleteNonCompletedProducts',

        'sStoreOpeningHours',
        'sEditOpeningHours',
        'sIndexOpeningHours',

        'sIndexAddresses',
        'sShowAddress',
        'sAddAddress',
        'sEditAddress',
        'sDeleteAddress',
        'sChangeDefaultAddress',

        'sShowShoppingCart',
        'sValidateProducts',
        'sAddShoppingCart',
        'sCheckCartAvailableQuantities',

        'sAddOrder',
        'sReceiveOrder',
        'sPurchaseOrders',
        'sSalesOrders',
        'sShowOrder',
        'sCancelOrder',
        'sApproveOrder',
        'sRejectOrder',
        'sOrderStatuses',
        'sReOrder',

        'sAddProduct',
        'sAddRetailProduct',
        'sMakeBrand',
        'sToggleFavoriteProduct',
        'sToggleShowProductToConsumer',
        'sFindProductByBarcode',
        'sCloneProduct',

        'sIndexStoreUsers',
        'sAddStoreUser',
        'sEditStoreUser',
        'sDeleteStoreUser',
        'sShowRolesForUserType',
        'sShowRolesForSelection',

        'sShowActivities',
        'sShowUserActivity',

        'sCreateLogos',
        'sEditLogos',
        'sDeleteLogos',
        'sShowSellerLogos',

        'sAddStoreSetting',
        'sShowStoreSetting',
        'sEditStoreSetting',
        'sDeleteStoreSetting',

        'sIndexStoreMeasurements',
        'sAddStoreMeasurements',
        'sEditStoreMeasurements',
        'sDeleteStoreMeasurements',

        'sStoreDashboardStatistics',

        'sListStoreNotifications',
        'sReadNotification',
        'sReadNotificationById',
        'sUnReadNotificationsCount',
    ]

];
